export const DISTRIBUTORS_LIST = [
  'DIGIMOTOS_SAS',
  'COLCAMER_SAS',
  'BMR_GROUP_SAS',
  'DIVERXA_SAS',
  'SUPERMOTOS_SAS',
  'MOTORENTING_SAS',
  'VELMOTOR_SAS',
  'SHIMOTO_SAS',
  'MH_MOTOS_SAS',
  'VENTO_MOTOS',
  'OTROS',
];
